PATH, versions and ctypes
zarch/grass-session pull request #14
Opened 2019-10-18 12:19 UTC by ninsbl

This PR adresses several issues:
 - PATH variable in os.environ grew with every session (now environment is cleaned up when session closes)
- it was not possible til load pygrass libraries that use ctypes. That should be possible now
- wehn starting a session, parameter "grassversion" had no effect. Now a session can be created with a specific GRASS version

Though it worked as expected on my system, this is is not tested thoroughly. Please review carefully before merging the PR.

2019-10-26 12:32 UTC, ninsbl commented
Currently, start with LOCALE and LC_ALL set to C  in `set_grass_path_env` is failing.
With LOCALE and LC_ALL set to en_US.UTF-8, everything works fine.
Unfortunately, en_US.UTF-8 is probably not available on all systems. So I did not change this default....
Any ideas?

2019-10-29 17:06 UTC, neteler commented on grass_session/session.py
> +        raise RuntimeError('No GRASS libraries found in {}.'.format(ld_path))
```suggestion
        raise RuntimeError('No GRASS GIS libraries found in {}.'.format(ld_path))
```

2019-10-29 17:07 UTC, neteler commented on grass_session/session.py
> +        raise RuntimeError('Could not load all the folowing GRASS libraries from {}!'.format(remains))
```suggestion
        raise RuntimeError('Cannot load all the following GRASS GIS libraries from {}!'.format(remains))
```

2019-10-29 17:08 UTC, neteler commented
@ninsbl Please also set the default version from grass74 to grass78

2019-11-21 05:31 UTC, zarch requested changes
@ninsbl Thank you for the work done.
I tested locally and I have few remarks.

all the best

2019-11-21 05:31 UTC, zarch commented on grass_session/session.py
> +    import glob
```suggestion
```
This `glob` variable is not used within the function so it should be not necessary.

2019-11-21 05:31 UTC, zarch commented on grass_session/session.py
> +load_libs(GISBASE)
Hi @ninsbl,

sorry for the delay but I didn't have time to carefully looking at this PR.
Testing locally your change I have an error that I do think is due to these lines.

The code that give me an issue is:
```python
from grass_session import Session
from grass.script import core as gcore
```
the error that generate is:
```bash
$ GRASSBIN=grass78 LOCAL=true DEBUG=true python3 test_gsess.py

GRASSBIN: grass78
GISBASE: /usr/lib64/grass78
Loading libraries from /usr/lib64/grass78/lib
Traceback (most recent call last):
  File "test_gsess.py", line 9, in <module>
    from grass.script import core as gcore
  File "/usr/lib64/grass78/etc/python/grass/__init__.py", line 21, in <module>
    _LOCALE_DIR = os.path.join(os.getenv("GISBASE"), 'locale')
  File "/usr/lib64/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The issue is that the `GISBASE` variable is not set as environmental variable.

```python
from grass_session import Session
import os
print("Current GISBASE is: ")
print(os.environ['GISBASE'])

from grass.script import core as gcore

```

And this is the error when executing the code:
```bash
$ GRASSBIN=grass78 LOCAL=true DEBUG=true python3 test_gsess.py

GRASSBIN: grass78
GISBASE: /usr/lib64/grass78
Loading libraries from /usr/lib64/grass78/lib
Current GISBASE is: 
Traceback (most recent call last):
  File "test_gsess.py", line 11, in <module>
    print(os.environ['GISBASE'])
  File "/usr/lib64/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'GISBASE'
```

As you can see the `GISBASE` key is not in `os.environ` and this is why GRASS is raising an issue on this line: 
```python
_LOCALE_DIR = os.path.join(os.getenv("GISBASE"), 'locale')
```

Why do you need to make a copy of the `os.environ` and not use the `os.environ` directly?
I give the possibility to pass a dictionary to use instead of the `os.environ` because it is useful when executing a job in a multi-processing and multi-mapset environment, but the idea that I had in mind was start a Session as master of the process, and then start N-mapsets where I can execute the n-processes in parallel on different nodes (if executed in a HPC context).

The get the current code running on my system I have to write:
```python
import os
from grass_session import Session
from grass_session.session import env

os.environ.update(env)
from grass.script import core as gcore
```
But it seems less ergonomic/friendly. So I would personally rollback to previous behaviour:

So change:
```python
env = os.environ.copy()
env = set_grass_path_env(GISBASE, env=env, grassbin=GRASSBIN)
load_libs(GISBASE)
```
into:
```python
set_grass_path_env(GISBASE, env=os.environ, grassbin=GRASSBIN)
load_libs(GISBASE)
```

2020-04-10 05:14 UTC, merged